### PR TITLE
[Fix] Added capital eszett and fixed default order in more keys

### LINKED ISSUE #495: German capital eszett
In the german layout the capital Eszett letter is missing.
It's not that big issue due to it's rarely used but for integrity it should be added.

screenshot

Additional info: [Wikipedia](https://en.wikipedia.org/wiki/%C3%9F#Development_of_a_capital_form)
U+1E9E ẞ LATIN CAPITAL LETTER SHARP S
It's part of unicode since 2007.

### LINKED ISSUE #657: 1.4.5 pre-selects wrong character below "s" for German layout
The new version 1.4.5 introduces a bug using the German layout:

Until now, when long-pressing "s", the "ß" character was pre-selected (as one would expect it and as it should be).

With 1.4.5, "#" is pre-selected when long-pressing "s" instead, and one has to navigate to get a "ß".

### PR DESCRIPTION
**Pull request by MajeurAndroid**
@UserX404 @l3u can you test the built apk and confirm us the issue is fixed ?

Fixes #495 
Fixes #657

### CODE REVIEW

**Comment by l3u** [comment]
Sure, where can I get it?

**Comment by MajeurAndroid** [comment]
@l3u See https://github.com/openboard-team/openboard/pull/545#issuecomment-1046267394.

**Comment by l3u** [comment]
I can't install it … something about Google Protect not recognizing the author?! Choosing "install anyway" doesn't install it as well … :-(

**Comment by UserX404** [comment]
@MajeurAndroid 

The akp isn't available
```
Download artifacts 

The following artifacts have expired and are no longer able to be downloaded.
```

**Comment by jnnkB** [comment]
I think the artifact is still available: https://github.com/openboard-team/openboard/suites/7783995641/artifacts/327805616. I found it on this site: https://github.com/openboard-team/openboard/pull/664/checks

**Comment by UserX404** [comment]
Thanks for the link @jnnkB
@MajeurAndroid
I've manually uninstalled 1.4.4 and installed the given 1.5.5.
I can confirm the 'ß' is back in its place.

**Comment by UserX404** [comment]
But the capital 'ẞ' is shown in capital and in upper- and lowercase suggestion. Is this intended?

**Comment by UserX404** [comment]
The artifact has expired.
Had to re-setup my phone and hadn't backed up the akp. 
Or even better, please create a new version for Fdroid!
ß-issue drives me crazy

**Review by Mxdon123 — APPROVED** [review]

**Pull request merged**
