### PR TITLE
[RFC] Adds Colemak Mod-DH keyboard layout

### LINKED ISSUE #170: Add Support for Colemak Mod-DH keyboard layout
https://colemakmods.github.io/mod-dh/

### PR DESCRIPTION
**Pull request by toniz4**
I have almost 0 experience with java/android development. So i need some help completing this. 

It works, but i think it needs translations, and i don't know how to do that.

https://colemakmods.github.io/mod-dh/

closes #170

Screenshot_20210213-194612_Bromite_1

### CODE REVIEW

**Comment by dslul** [comment]
@toniz4 if you fix that small typo I can add this to the next release.

**Comment by toniz4** [comment]
> @toniz4 if you fix that small typo I can add this to the next release.
Sorry, which small typo?

**Comment by dslul** [comment]
On line 81 (c%s (Bépo)), I left a comment above.

**Comment by toniz4** [comment]
done.

**Pull request merged**
