### PR TITLE
Added Swedish and Danish dictionaries

### PR DESCRIPTION
**Pull request by so9q**
I did not test the app with these. Do you want me to test them?

### CODE REVIEW

**Comment by roshavagarga** [comment]
@so9q Best to test and ping again I guess?

**Comment by dslul** [comment]
@so9q yes please, I cannot merge otherwise

**Comment by jpds** [comment]
@dslul I'm happy to test both of these if you can provide me with a test .apk.

**Comment by TheCrowned** [comment]
I tested both and they work fine! Would be lovely to see this merged! :)

**Comment by dslul** [comment]
@so9q could you also provide the non-binary files, in case something needs to be modified?

**Pull request merged**
