### PR TITLE
Replaced previous Bengali (Bangladesh) keyboard with a popular layout

### PR DESCRIPTION
**Pull request by RHJihan**
The previous Akkhor keyboard for Bengali (Bangladesh) is not popular in Bangladesh at all. It is on AOSP like "taken for granted". The so-called Unijoy layout is most popular in Bangladesh, which I replaced (added) in is pull request.

The Unijoy layout is also in The m17n Library. (https://www.nongnu.org/m17n/manual-en/m17nDBData.html)

### CODE REVIEW

**Comment by dslul** [comment]
Thank you. If the akkhor layout is still used by someone, I guess it'd be better to keep it. Could you do this change?

**Comment by RHJihan** [comment]
I know there's very little chance of this. But as a Bangladeshi, I know most people use Phonetic Bengali keyboards. People who type Bengali both on the Computer, and phone, most of them prefer this so-called Unijoy layout. (As this layout is the most popular layout for fixed Bengali typing on the computer.) The rest prefer a keyboard named "Probhat."
I guess the number of users of Akkhor is near zero. This layout is kind of depreciated in Bengali typing. 

Event than I can keep that if you wish. So, should I do this on another pull request?

**Comment by dslul** [comment]
Ok you convinced me, you can leave it as it is. Have you tested this change?

**Comment by RHJihan** [comment]
Actually, I did this before on another keyboard based on OpenBoard. That works fine. 
But I did not build this commit. I will check this and let you know if something wrong.

**Comment by RHJihan** [comment]
My bad. I checked this. Works fine but a minor alignment problem found on second row of layout. 
I will fix this as soon as possible.

**Comment by RHJihan** [comment]
Hello again. I checked this commit on the emulator. And it works perfectly. Just a little tweak.

**Comment by dslul** [comment]
Great, thanks!

**Comment by Oymate** [comment]
I have muscle memory with akkhor layout, so I hope it stays as an option

**Comment by RHJihan** [comment]
@Oymate, okay. There is an option for `Custom input styles` to add more layouts. I hope I can try to add _Akkhor_ and _Probhat_ layout to this.

**Comment by Oymate** [comment]
It's okay if bijoy is the default, as long as akkhor remains an option

**Comment by RHJihan** [comment]
@Oymate, I added _Akkhor_ layout on this pull request #408 
This can be enabled directly from `Languages` (not `Custom input styles`) named _Bangla (Bangladesh) (Akkhor)_.
_Probhat_ is not introduced.

**Comment by Oymate** [comment]
@RHJihan I think the implemented Jatiyo layout is a bit different than the official one.  As can be seen from your research paper: https://www.researchgate.net/publication/342529679_Documentation_on_Bengali_Computer_Keyboard_Layout

**Comment by RHJihan** [comment]
@Oymate, The implemented layout is _Unijoy_ from the [m17n database](https://www.nongnu.org/m17n/manual-en/m17nDBData.html) (4.11. on my article). The layout is slightly modified on OpenBoard for the mobile-friendly experience, i.e. _dari, chandrabindu, khanda-ta_ position.

**Comment by Oymate** [comment]
@RHJihan Check the ক/খ and ব/ভ button specifically. These have been switched.(They need to be switched back)

**Comment by RHJihan** [comment]
@Oymate, This is not the _Jatiyo (National) Keyboard layout_ in the first place. This is the Unijoy Layout. You can see that _ya phala_ & _ra phala_ position is also different on this layout than Jatiyo.

**Pull request merged**
