### PR TITLE
Added ß to German Layout

### PR DESCRIPTION
**Pull request by mahmoudk1000**
- Added ß to German Layout
German layout was missing it. BTY i tested it, it does work fine.

### CODE REVIEW

**Comment by UserX404** [comment]
This issue has been already fixed but devs won't create a new release for whatever reason.

https://github.com/dslul/openboard/commit/ec55fc09aa02d968274f50a690aa4d99a7520859

**Comment by mahmoudk1000** [comment]
@UserX404 mine is different. My edition is to make it in its own botton. Considered as umlaut letters they are separated in their own buttons.

**Comment by dslul** [comment]
> This issue has been already fixed but devs won't create a new release for whatever reason.

The reason is time, but I did it yesterday


> * Added ß to German Layout
>   German layout was missing it. BTY i tested it, it does work fine.

is it common to have this key as separate in the german layout? I want to get the approval of someone else before merging language-specific things now because last time I merged something in the german layout someone loudly complained and now writes everywhere that I "messed up" :)

**Comment by mahmoudk1000** [comment]
@dslul yes it's commonly yes. I saw on AnyTypeKeyboard and florisboard keyboard too. Both have as separate key.

**Comment by dslul** [comment]
> @dslul yes it's commonly yes. I saw on AnySoftKeyboard and florisboard keyboard too. Both have as separate key.

What about GBoard?
Let's see what the other german people think about this change (@kojid0 and I think also @sandsturm ?)

**Comment by mahmoudk1000** [comment]
@dslul I just checked gboard. It doesn't have as separate key. They added it under letter S. But I would like to hear other guys too. In my opinion as separate key is more functional.

**Comment by UserX404** [comment]
> 
> Let's see what the other german people think about this change (@kojid0 and I think also @sandsturm ?)

I don't need an extra key for 'ß'. I'm absolutly fine if it's back at the first popup position of 's'.
AOSP Keyboard also have no extra key.

**Comment by mahmoudk1000** [comment]
Herr how it Looks with separated key. Bty in capital case its works fine in all capital cases(shifted, etc..)

**Comment by kojid0** [comment]
> Let's see what the other german people think about this change (@kojid0 and I think also @sandsturm ?)

I don't need a special key, I'm fine with long pressing "s".

**Comment by samarutuk** [comment]
…and I just wanted to open an (new) issue, whether you could use the space in the bottom row next to the letter M for a ß 🙈 (I have long used the "Deutsche Tastatur" (German Keyboard) on Google Play where this was already so).
If you have a keyboard layout with extra keys for the umlauts (ä, ö, ü), then ß should also have an extra key. The purpose of this extra layout is to be able to type German **without any delay**. Otherwise you can stay with the reduced layout with pressing longer for all special characters (ä, ö, ü, ß) of the German language.
I say this as a native German speaker who prefers to type without the autocorrect option and without the slowdown caused by pressing a key for a longer time. So thumbs up for the above layout (which even has a capital ß) 👍

**Comment by mahmoudk1000** [comment]
@samarutuk I totally agrees with you. That is my point from the start. Sad that few people don't like it.
I hope to hear from dev for his opinion and decision about this.

**Pull request merged**
