### PR TITLE
Fix suggestion, and optimize keyboard height

### LINKED ISSUE #660: Suggestions not showing everywhere.
**Description**
Suggestions should be shown everywhere except in password fields with PR #562. But in several apps, word suggestions are not showing, i.e. Facebook Messenger, Microsoft Edge, Google Play Store, Contact (Samsung), Google Maps, Spotify, Galaxy Store, Keepass2Android, and so on. 

**Screenshots**
<table style="width:100%; border: none;">
  <tr>
    <td style="border: none;"></td>
    <td style="border: none;"></td>
    <td style="border: none;"></td>
    <td style="border: none;"></td>
  </tr>
<tr>
    <td style="border: none;"><figcaption>Google Play Store</figcaption></td>
    <td style="border: none;"><figcaption>Google Maps</figcaption></td>
    <td style="border: none;"><figcaption>Spotify</figcaption></td>
    <td style="border: none;"><figcaption>Galaxy Store</figcaption></td>
  </tr>
</table>

**Smartphone**
 - Device: Samsung Galaxy m32 (SM-M325F)
 - OS: Android 12 (One UI 4.1)
Tested OpenBoard version 1.4.5 (form F-Droid)

**Possible Solution**
https://github.com/openboard-team/openboard/blob/e9393dfab01dcdfb0872f360b1afe8092777f5ec/app/src/main/java/org/dslul/openboard/inputmethod/latin/InputAttributes.java#L108
This can be changed to `mShouldShowSuggestions = !mIsPasswordField;`
https://github.com/openboard-team/openboard/pull/562#issuecomment-1073459339

### PR DESCRIPTION
**Pull request by odmfl**
optimize keyboard height,and fix suggestions
problems not visible in many apps like
playstore, kiwi browser, etc

Fix #660 #745 #747 #731 #275 #418 #507 #345

### CODE REVIEW

**Comment by RHJihan** [comment]
As far as I have tested, the suggestion strip is not showing on Google Chrome, Facebook Messenger, Samsung Contacts, and [Keepass2Android](https://github.com/openboard-team/openboard/issues/660#issuecomment-1214290321).

<table style="width:100%; border: none;">
  <tr>
    <td style="border: none;"></td>
    <td style="border: none;"></td>
    <td style="border: none;"></td>
<td style="border: none;"></td>
  </tr>
<tr>
    <td style="border: none;"><figcaption>Google Chrome</figcaption></td>
    <td style="border: none;"><figcaption>Facebook Messenger</figcaption></td>
<td style="border: none;"><figcaption>Samsung Contacts</figcaption></td>
<td style="border: none;"><figcaption>Keepass2Android</figcaption></td>
  </tr>
</table>

**Comment by odmfl** [comment]
@RHJihan You don't have to write in the address bar of the browser, only it doesn't appear there, but it doesn't appear with the aosp keyboard either.  Then that should only be used to type a manual url, go to the google or other page and write from there.

**Comment by odmfl** [comment]
before even looking on the play store it didn't work, however I will do some tests and see if I can solve it

**Comment by RHJihan** [comment]
I wanted to see this from a user's point of view. As a user, I would prefer to see suggestions everywhere as I get them on _Gboard_ or _Samsung Keyboard_. 
If the AOSP keyboard works the same, I think it should not be implemented as it is.

**Comment by Helium314** [comment]
The keyboard changes are basically reverting #562 and adding even more restrictions, so of course the old problems are back again.

I think the only real fix is #709, so there needs to be a setting...

**Comment by odmfl** [comment]
Ok, I did this and now it works for all of them, however with commit #562 it didn't work for me either on the play store, for this reason I had done a sort of revert, then it worked for me on the playstore and others and I thought it was solved, now I did as you suggested and it works perfectly.  It just has to be merged.  However there are 2 PRs of mine almost duplicates, I think I will close this one and do everything in the other one.  Try the apk and let me know

https://github.com/odmfl/openboard/suites/10183816163/artifacts/498264752

**Comment by RHJihan** [comment]
Yes, the last fix works perfectly.

**Comment by RHJihan** [comment]
@odmfl, did you add this [commit](https://github.com/odmfl/openboard/commit/739a8dde37d56f961ffdbafa707d674998d8e340) to this PR yet?

**Comment by odmfl** [comment]
full PR is #749, 750 is a copy and should be deleted

**Comment by RHJihan** [comment]
@odmfl, so you would like to close this PR.

**Pull request closed without merging**
