### PR TITLE
Enable split layout for QWERTZ keyboard layout set

### LINKED ISSUE #191: Split keyboard does not work with other languages
Split keyboard functions only with English USA, not any other language.

### PR DESCRIPTION
**Pull request by derhagen**
Resolves #191 for QWERTZ

### CODE REVIEW

**Comment by dslul** [comment]
Thanks for the PR. Have you already tested it?

**Comment by derhagen** [comment]
> Thanks for the PR. Have you already tested it?

Yes

**Comment by derhagen** [comment]
@dslul Does it make sense to hand this in here as well? https://android.googlesource.com/platform/packages/inputmethods/LatinIME/

**Comment by dslul** [comment]
You can if you want, but the aosp keyboard is abandoned; as of now, it's more like a starting point for new keyboards.

**Pull request merged**
