### PR TITLE
Updated emoji support

### LINKED ISSUE #6: Consolidate emoji skin tones
The emoji list in this keyboard has the same issue as the AOSP keyboard: every emoji that has multiple skin tones available shows each skin tone as a separate item in the list. This makes the emoji list extremely cluttered and difficult to navigate. Other keyboards allow a long-press on the default yellow emoji to choose a skin tone. That might be the best approach. Or you could choose a default skin tone in the settings and only display that skin tone in the list.

### LINKED ISSUE #144: Please add more classical text smileys or even better let the user add them
I personally love to still use the classic text smileys, like :-) or ;-) or :-D or :-( or :'-( and so on. Currently, the emoticon selection dialog only lists a few of those new-fangled unicode ones (flipping table over).

I'd really love to be able to select the classical ones there, the very best thing would be if one could define own smileys to be shown.

Along with issue #61 and #6 , this would imo greatly improve the usability of the emoticon dialog.

### LINKED ISSUE #157: Missing Emojis
Some emojis are missing from emoji's menu. Eg: 🥺 🥵 🥶

### LINKED ISSUE #216: Add an favorite tab for emojis.
Add an favorite tab for emoji's. because too much emoji's are available and we use some particular emoji's.
And recent tab is not enough.
Recent tab can stores little bit of emoji's.

### PR DESCRIPTION
**Pull request by MajeurAndroid**
These changes seem massive but most of file changes are multiple config drawable changes due to updating emoji categories icons..

I'll try my best to give context to each major change, which I tried to group in relevant commits to make review easier:
### Extended 'more keys' support to emoji keyboards (4432aa3)
These changes consist in implementing support for what is called 'more keys' feature into emoji keyboard. To avoid reinventing the wheel and keep project away from new bugs, every component used to do so are from base keyboard (MoreKeysKeyboard, MoreKeysKeyboardView etc...). In fact, only touch input logic to detect (long) presses needed to be wrote (which is fairly simple).
Also, an array based 'more keys' specification has been added (inspired from what already exists with codesArray/textsArray) to define 'more keys' data for each emoji code point.
Major changes are in EmojiPageKeyboardView and KeyboardBuilder classes.

### Updated emoji categories to Unicode 12.0+ ones (fed9f97)
Since Unicode 12.0, emojis grouping recommendations have changed. Most of changes in this commit are due to category icon changes. As app's minsdk is now 19, support for previous emoji versions has been dropped, leading to most of categories being obsoletes. We have now 10 categories including recents and emoticons.
A toggle in settings allowing user to enable/disable emoticons tab would be nice.

### Added all emojis up to Unicode 13.1 (19917e1)
This one only deals with emoji-categories.xml, which now includes every emojis up to Unicode 13.1 version. Support for per emoji min sdk version definition already existed and is now used to make emojis available only on devices that can render them.

2 remaining commits do not need further description.

Here is a screen capture of the keyboard on a device running platform level 29:
keyboard_demo

This fixes #216, fixes #157 and fixes #6 (and also fixes #144).

### CODE REVIEW

**Comment by dslul** [comment]
This was unexpected, thank you!

**Comment by Happyfeet01** [comment]
When would it release to F-Droid Store? Or build myself?

**Comment by dslul** [comment]
> When would it release to F-Droid Store? Or build myself?

There is a small bug that needs to be fixed first before releasing (when inserting emojis that have more colors they appear invisible sometimes).
@MajeurAndroid do you also have this issue?

**Comment by MajeurAndroid** [comment]
No, I haven't encountered this bug at all. For which emojis and on which Android version does this occur?

**Comment by MajeurAndroid** [comment]
Also I think their is something off with categories index or something, when clicking on an emoji tab, the page shown isnt the first one of the category sometimes..

**Comment by chaptergy** [comment]
@dslul If I remember correctly I have also observed the invisible-emoji issue with e.g. the telegram emoji keyboard. So I'm assuming this is an issue with android instead of openboard. What I can say for certain is, that I have observed this issue in the past, so it is not caused by something in this version. However in my personal opinion this is a minor issue.

**Comment by dslul** [comment]
> @dslul No, I haven't encountered this bug at all. For which emojis and on which Android version does this occur?

Android 10, but it looks like it only happens when using Telegram. I need to investigate more on this issue. Regarding the other issue, you're right, looks like the current index is set to the last used page (where you used your last emoji).

**Comment by rajki** [comment]
@dslul Is there something that I can do to assist with the next release? Holding my breath for this feature. Emojis is the only pain point for me in the latest available release.

**Comment by bennypr0fane** [comment]
This still does not appear to be released on F-Droid. Is it a part of the current release, which just hasn't made it to F-Droid yet, or will it be going in to the next one? Timeline, anyone...?

**Comment by duyfken** [comment]
> This still does not appear to be released on F-Droid. Is it a part of the current release, which just hasn't made it to F-Droid yet, or will it be going in to the next one? Timeline, anyone...?

It will be in the next master release as this was merged into the master in Dec 2020 (the last stable release 1.4.2 was in Oct 2020)... the most recent beta release was 2 days after this was merged, so if you want the updated emoji support before the next stable release, [get the 1.4.3 beta](https://github.com/dslul/openboard/releases/tag/1.4.3-BETA).

**Pull request merged**
