### PR TITLE
Fix german layout

### PR DESCRIPTION
**Pull request by kojid0**
Fix key hint for letter s (#211)

### CODE REVIEW

**Comment by dslul** [comment]
Did you test this change?

**Comment by kojid0** [comment]
> Did you test this change?

no. I try to close #210 and maybe other issues first and then I test soon. Probably tomorrow.

**Comment by kojid0** [comment]
Just tested it and this fixed the issue. Unable to fix #210 though.

**Comment by UserX404** [comment]
@kojid0 
Can you please pack this changes into the next release?
It seems it's not included in the latest beta.

Thank you

**Comment by Glitchy-Tozier** [comment]
This would be really important to finally get access to.

**Pull request merged**
