### PR TITLE
Compress dictionaries and allow users to add more

### LINKED ISSUE #47: Reduce size of package
There is no reason a simple keyboard should be 24MB. Even complicated apps are less than 10MB.

Looking at other keyboard packages for reference:
- openboard-1.3.apk 24 MB
- hackerskeyboard-v1.41.1.apk 2.57 MB
- AnySoftKeyboard 5.77 MB
- BeHe Keyboard 1.0 MB

One clear misuse is adding All dictionaries directly.
Which is why having the ability to add-on dictionaries is important. Not everyone wants nor uses all dictionaries.
https://github.com/dslul/openboard/tree/master/app/src/main/res/raw

Adding more dictionaries will keep increasing size of apk, by around 1mb per dictionary.
Having a way to import dictionaries manually will help reduce the size.

### LINKED ISSUE #219: feature request: add dictionaries from the application
most keyboards support selecting and installing dictionaries from their settings, why shouldn't this one too ?

### LINKED ISSUE #355: Question: OpenBoard vs Florisboard
Currently I evaluate again OpenBoard and Florisboard. Personally I like OpenBoard more, but Florisboard has some nice features, like Clipboard view for example.

What I didn't completely understand is the huge size difference of the package. Florisboard is around 7 MB and OpenBoard around 45. Is this only the size of the dictionaries included in the main package? Are there other main differences?

### PR DESCRIPTION
**Pull request by Helium314**
Compressed files can't be read directly by the native library, so the dictionaries were uncompressed so far.
This PR changes the behavior a bit, so the content of an accessed dictionary is copied to internal files directory when the dictionary is loaded for the first time.
Loading from internal files directory is current behavior anyway, so on further loads the dictionary is loaded from there.

Locale matching is done like previously, so always the same locale should be selected.

Sort of fixes #47, though even the compressed size is now 30 MB and thus bigger than the 24 MB in the initial complaint.

Anyway, further size reduction should be possible by removing some dictionaries and allowing to load dictionaries from files, which would simply copy the content to internal files directory to the correct locale. But the user would have to download dictionaries manually.

[Edit: change title and link issues]
fixes #355 
fixes #219

### CODE REVIEW

**Comment by Helium314** [comment]
> allowing to load dictionaries from files, which would simply copy the content to internal files directory to the correct locale

I just tried this: it was quite simple to implement and doesn't require any new permissions (using `Intent.ACTION_OPEN_DOCUMENT` and storage access framework)
I'll upgrade the PR once the code is a bit cleaner.

Rough sketch of UI:
Add some "add dictionary" preference, opens a dialog when clicked.
Dialog tells user that they can choose a dictionary file, and provides a link to where they can be downloaded (maybe some folder in the repo?).
When a file is picked there is another dialog:
* informs that dictionary was added for _locale_
* maybe: asks whether existing dicionary should be overwritten (only if new version is older?)
* informs about any errors

@MajeurAndroid / @dslul is that approach ok?

**Comment by dslul** [comment]
Looks good to me, thanks a lot for the effort!

**Comment by Helium314** [comment]
Great!
So this works now.

Three things that may or may not need a change:
* Currently there is no way of deleting dictionaries added by the user, e.g. because a dictionary turns out to be worse than default. The only way of going back to default is by downloading the default dictionary.
* Better locale match is always preferred. If a user with *pt_br* adds a dictionary for _pt_, the new dictionary would never be used as *pt_br* already exists. I don't know what could be done here, but at the same time I think it is not really likely to actually happen. Thus I'm inclined to leave this as it is.
* I point the users to https://github.com/openboard-team/openboard/ for downloading dictionaries, which is currently wrong / not useful. But I guess this will improve quickly as there seem to be several dictionaries ready (looking at other PRs).

**Comment by Helium314** [comment]
I'm going to implement a proper preferences screen for showing, adding, updating and deleting dictionaries.
Interstingly my worst problem is getting a proper icon... help on finding something is highly appreciated!

**Comment by MajeurAndroid** [comment]
This looks really good, I wanted to do this for a long time, nice one.
We'll do another branch for this too, as it's a big and I think really long-awaited feature. So we can make sure it's OK before merging it.
For the icons, don't bother, you can use dummy existing ones, I'll import new ones later, I have some toolings to support this old icon format.

**Comment by Helium314** [comment]
@MajeurAndroid is there anything I can do to get this implemented?

**Comment by Helium314** [comment]
@MajeurAndroid @dslul I don't want to be annoying, but considering the number of open issues / PRs regarding dictionaries, adding dictionaries from a file has the potential to help a lot of people.

What needs to be done to get this feature (and fix #578) into the main branch?

**Pull request merged**
